version: "3.9"

networks:
  algalog-netwok:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    networks:
      - algalog-netwok

  algalog-api:
    image: algalog-api
    environment:
      DB_HOST: algafood-mysql
    ports:
      - "8080:8080"
    networks:
      - algalog-netwok
    depends_on:
      - algafood-mysql
